export { default as NpmVersion } from './NpmVersion.svelte'
export { default as GitHub } from './GitHub.svelte'
export { default as NpmDownloads } from './NpmDownloads.svelte'
export { default as GitHubDownloads } from './GitHubDownloads.svelte'
export { default as NpmAuthorDownloads } from './NpmAuthorDownloads.svelte'
export { default as PypiVersion } from './PypiVersion.svelte'
export { default as StaticBadge } from './StaticBadge.svelte'
export * from './types'