export { default as Download } from './Download.svelte'
export { default as GitHub } from './GitHub.svelte'
export { default as GitHubDownload } from './GitHubDownload.svelte'
export { default as GitHubSponsor } from './GitHubSponsor.svelte'
export { default as JsrVersion } from './JsrVersion.svelte'
export { default as License } from './License.svelte'
export { default as NpmAuthorDownload } from './NpmAuthorDownload.svelte'
export { default as NpmDownload } from './NpmDownload.svelte'
export { default as NpmVersion } from './NpmVersion.svelte'
export { default as PypiVersion } from './PypiVersion.svelte'
export { default as StaticBadge } from './StaticBadge.svelte'
export { default as Version } from './Version.svelte'
export * from './types'